# Version of Docker-compose for this Flask Load balancing application
version: '4'
services:
  # Add the Flask application Service
  app:
  # Location of the Flask Application dockerfile
    build: 
      context: app
    image: webapp
    container_name: test-web-app
    ports:
       # Flask application Host port: Flask Container port
      - '5000'
  # nginx service
  nginx: 
  # The official nginx Docker from Docker Hub. For building the nginx container
    image: nginx:latest
    volumes:
    # Volume for the nginx Docker container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # The nginx service depends on the Flask application service (It will link the Flask web application and Nginx Load balancer)
    depends_on:
      - app
    # ports for the nginx application service
    ports:
    # Port for the Nginx load balancer
      - "80:80"
