version: '3.8'

services:
  app1:
    build: 
      context: ./app
      dockerfile: Dockerfile.flask  # The Dockerfile for the custom app
    image: webapp
    container_name: app1
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
  app2:
    build: 
      context: ./app
      dockerfile: Dockerfile.flask  # The Dockerfile for the custom app
    image: webapp
    container_name: app2
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
  app3:
    build: 
      context: ./app
      dockerfile: Dockerfile.flask  # The Dockerfile for the custom app
    image: webapp
    container_name: app3
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
